# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bda94fe9d813bc0d98c508b102327fb63b6a1ab05fd5ffea5eef7d969106d6c977fa13d24878b9569fcfcbd0483eb73042e21a1ea2542c1d7e151a707873bc42

test:
  secret_key_base: 9806337b6674563331178714d7a42741b3656b9a885de672c6ec9ce8f61ecbc6073143969524d139a8d3d81a3bfa8e5daffa508342d31589850d5471dd5354ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
